use std::collections::HashMap;
use std::fs;
use std::path::Path;
use w3strings::{decode, encode, hash_key};

#[test]
fn test_w3strings_integration() {
    let test_file_dir = Path::new("test-file");
    let en_w3strings_path = test_file_dir.join("en.wstrings");
    
    // Output paths
    let en_rust_wstrings_csv_path = test_file_dir.join("en-rust.wstrings.csv");
    let en_w3strings_csv_path = test_file_dir.join("en.wstrings.csv");
    let en_rust_w3strings_path = test_file_dir.join("en-rust.w3strings");
    let en_rust_w3strings_csv_path = test_file_dir.join("en-rust.w3strings.csv");

    assert!(en_w3strings_path.exists(), "test-file/en.wstrings not found");

    // w3strings.exe path check
    let exe_path = if test_file_dir.join("w3strings.exe").exists() {
        test_file_dir.join("w3strings.exe")
    } else {
        Path::new("w3strings.exe").to_path_buf()
    };

    // ==========================================
    // 1次テスト (Primary Test)
    // ==========================================
    println!("Starting Primary Test...");

    // 1. en.wstringsに対し、w3strings.exeで「w3strings.exe -d en.wstrings」を実行し、en.wstrings.csvを出力させる
    if en_w3strings_csv_path.exists() {
        fs::remove_file(&en_w3strings_csv_path).unwrap();
    }
    let output1 = std::process::Command::new(&exe_path)
        .arg("-d")
        .arg(&en_w3strings_path)
        .output()
        .expect("Failed to execute w3strings.exe for en.wstrings decoding");
    
    assert!(
        output1.status.success(),
        "w3strings.exe failed to decode en.wstrings: {}",
        String::from_utf8_lossy(&output1.stderr)
    );
    assert!(en_w3strings_csv_path.exists(), "en.wstrings.csv was not generated by w3strings.exe");

    // 2. en.wstrings.csv からハッシュ辞書を構築
    let original_csv_content = fs::read_to_string(&en_w3strings_csv_path).unwrap();
    let mut hash_dict = HashMap::new();
    for line in original_csv_content.lines() {
        if line.starts_with(';') || line.trim().is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.splitn(4, '|').collect();
        if parts.len() >= 3 {
            let key_str = parts[2].trim();
            if !key_str.is_empty() {
                let hash = hash_key(key_str);
                hash_dict.insert(hash, key_str.to_string());
            }
        }
    }

    // 3. en.wstringsに対し、decodeを実行してen-rust.wstrings.csvを出力させる
    let original_binary = fs::read(&en_w3strings_path).unwrap();
    let decoded_csv = decode(&original_binary, &hash_dict).unwrap();
    fs::write(&en_rust_wstrings_csv_path, &decoded_csv).unwrap();
    assert!(en_rust_wstrings_csv_path.exists(), "en-rust.wstrings.csv was not created");

    // 4. 両者を比較して差が無ければ1次テスト成功
    let norm_original = original_csv_content.replace("\r\n", "\n");
    let norm_decoded = decoded_csv.replace("\r\n", "\n");

    let orig_lines: Vec<&str> = norm_original.lines().collect();
    let dec_lines: Vec<&str> = norm_decoded.lines().collect();

    assert_eq!(orig_lines.len(), dec_lines.len(), "Line count mismatch between original and decoded CSV");
    for (idx, (orig, dec)) in orig_lines.iter().zip(dec_lines.iter()).enumerate() {
        let clean_orig = orig.replace('"', "");
        let clean_dec = dec.replace('"', "");
        assert_eq!(
            clean_orig, clean_dec,
            "Mismatch at CSV line {}!\nExpected: {}\nGot:      {}",
            idx + 1, orig, dec
        );
    }
    println!("Primary Test passed successfully!");

    // ==========================================
    // 2次テスト (Secondary Test)
    // ==========================================
    println!("Starting Secondary Test...");

    // 1. en-rust.wstrings.csvに対し、encodeを実行してen-rust.w3stringsを出力させる
    let encoded_binary = encode(&decoded_csv).unwrap();
    fs::write(&en_rust_w3strings_path, &encoded_binary).unwrap();
    assert!(en_rust_w3strings_path.exists(), "en-rust.w3strings was not created");

    // 2. w3strings.exeで「w3strings.exe -d en-rust.w3strings」を実行し、en-rust.w3strings.csvを出力させる
    if en_rust_w3strings_csv_path.exists() {
        fs::remove_file(&en_rust_w3strings_csv_path).unwrap();
    }
    let output2 = std::process::Command::new(&exe_path)
        .arg("-d")
        .arg(&en_rust_w3strings_path)
        .output()
        .expect("Failed to execute w3strings.exe for en-rust.w3strings decoding");

    assert!(
        output2.status.success(),
        "w3strings.exe failed to decode en-rust.w3strings: {}",
        String::from_utf8_lossy(&output2.stderr)
    );

    // 3. デコードに成功（en-rust.w3strings.csv が出力）すれば2次テスト成功
    assert!(en_rust_w3strings_csv_path.exists(), "en-rust.w3strings.csv was not generated by w3strings.exe");
    println!("Secondary Test passed successfully!");
}
